[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vic2_save"
version = "0.1.1"
requires-python = ">=3.11,<3.14"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "requests",

    "tqdm",
    "argcomplete",
    "userpath",

    "pyradox-txt-parser",
]

[dependency-groups]
dev = [
    "black",
    "ruff",
    "flake8",
    "pytest",
    "pyinstaller",
    "watchdog",

    "ipython",
    "ipykernel"
]
ml = [
    "torch==2.11.0+cu126",
    "torchaudio==2.11.0+cu126",
    "torchvision==0.26.0+cu126",

    "numpy",
    "pandas",
    "matplotlib",
    "sympy"
]   

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchaudio = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }

[tool.setuptools.packages.find]
where = ["."]
include = ["backend", "backend.*"] 