name: Commit and Check
on:
  push:
    branches:
     - dev
     - ai

jobs:
  build-windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Instal Deps        
        run: |
          uv sync --group dev 

      - name: Formattig
        run: |
          cd backend
          uv run ruff format .
          
      - name: Run Tests
        working-directory: backend/tests
        run: 
          uv run pytest test.py
